Fabula.Web/Controllers/CommentController.cs
namespace Fabula.Web.Controllers;

using Core.Contracts;
using ViewModels.Comment;
using Infrastructure.Utilities;

using static Common.Messages.LoggerMessages;
using static Common.Messages.NotificationTypes;
using static Common.Messages.ErrorMessages.Shared;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using System.Security.Claims;

public class CommentController : BaseController
{
    private readonly ICommentService commentService;

    private readonly ILogger logger;

    public CommentController(ICommentService commentService, ILogger<CommentController> logger)
    {
        this.commentService = commentService;
        this.logger = logger;
    }

    public async Task<IActionResult> All(string compositionId)
    {
        try
        {
            CommentsAllViewModel? commentViewModels = await commentService.GetAllByIdAsync(compositionId);

            if (commentViewModels == null)
            {
                TempData[WarningNotification] =
                    string.Format(ResourceNotFoundErrorMessage, GetControllerName().ToLower());

                return RedirectToAction("HandleErrors", "Error", new { statusCode = 404 });
            }

            return View(commentViewModels);
        }
        catch (Exception e)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            logger.LogWarning(
                LogMessageFormatter.FormatWarningLogMessage(Warning, e, userId, GetControllerName(), GetActionName()));

            TempData[ErrorNotification] = GeneralErrorMessage;

            return RedirectToAction("HandleErrors", "Error", new { statusCode = 500 });
        }
    }
}

Fabula.Web/Controllers/CompositionController.cs
namespace Fabula.Web.Controllers;

using Core.Contracts;
using Core.ServiceModels;
using ViewModels.Composition;
using Infrastructure.Utilities;

using static Common.GlobalConstants;
using static Common.Messages.LoggerMessages;
using static Common.Messages.NotificationTypes;
using static Common.Messages.ErrorMessages.Shared;
using static Common.Messages.SuccessMessages.Shared;
using static Common.Messages.ErrorMessages.Composition;
using static Common.Messages.ErrorMessages.Authorization;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

public class CompositionController : BaseController
{
    private readonly IGenreService genreService;

    private readonly ICompositionService compositionService;

    private readonly IUserService userService;

    private readonly IAccountService accountService;

    private readonly ILogger logger;

    public CompositionController(
        IGenreService genreService,
        ICompositionService compositionService,
        IUserService userService,
        IAccountService accountService,
        ILogger<CompositionController> logger)
    {
        this.genreService = genreService;
        this.compositionService = compositionService;
        this.userService = userService;
        this.accountService = accountService;
        this.logger = logger;
    }

    [HttpGet]
    [AllowAnonymous]

    public async Task<IActionResult> All([FromQuery] CompositionQueryModel query)
    {
        CompositionQueryModel? compositionQueryModel = null;

        try
        {
            compositionQueryModel = await compositionService.GetAllAsync(
                    query.SelectedGenres,
                    query.UserId,
                    query.SearchTerm,
                    query.CurrentPage,
                    query.CompositionsPerPage,
                    query.DateSorting,
                    query.RatingSorting);

            if (query.UserId != null)
            {
                compositionQueryModel.UserId = query.UserId;
                compositionQueryModel.Username = await userService.GetUsernameAsync(query.UserId);
            }

            compositionQueryModel.Genres = await genreService.GetAllForSelectAsync();
        }
        catch (Exception e)
        {
            string? userId = userService.GetUserId();

            logger.LogWarning(
                LogMessageFormatter.FormatWarningLogMessage(Warning, e, userId, GetControllerName(), GetActionName()));

            TempData[ErrorNotification] = GeneralErrorMessage;

            return RedirectToAction("HandleErrors", "Error", new { statusCode = 500 });
        }

        compositionQueryModel.CurrentPage = query.CurrentPage;

        return View(compositionQueryModel);
    }

    [HttpGet]

    public async Task<IActionResult> Create()
    {
        CompositionFormModel compositionFormModel = new CompositionFormModel();

        try
        {
            compositionFormModel.GenresToSelect = await genreService.GetAllForSelectAsync();
        }
        catch (Exception e)
        {
            string? userId = userService.GetUserId();

            logger.LogWarning(
                LogMessageFormatter.FormatWarningLogMessage(Warning, e, userId, GetControllerName(), GetActionName()));

            TempData[ErrorNotification] = GeneralErrorMessage;

            return RedirectToAction("HandleErrors", "Error", new { statusCode = 500 });
        }

        return View(compositionFormModel);
    }

    [HttpPost]

    public async Task<IActionResult> Create(CompositionFormModel formModel)
    {
        try
        {
            if (!ModelState.IsValid)
            {
                formModel.GenresToSelect = await genreService.GetAllForSelectAsync();

                ModelState.AddModelError("", "Invalid input when creating composition!");

                TempData[ErrorNotification] = InvalidInputDataErrorMessage;

                return View(formModel);
            }

            string? userId = userService.GetUserId();

            if (userId == null)
            {
                formModel.GenresToSelect = await genreService.GetAllForSelectAsync();

                TempData[ErrorNotification] = FailedCreatingCompositionErrorMessage;

                return View(formModel);
            }

            string compositionId = await compositionService.AddAsync(formModel, userId);

            await genreService.AddToCompositionAsync(compositionId, formModel.Genres);

            TempData[SuccessNotification] =
                string.Format(SuccessfulResourceCreationMessage,
                GetControllerName().ToLower(),
                formModel.Title);

            return RedirectToAction("Read", new { CompositionId = compositionId });
        }
        catch (Exception e)
        {
            string? userId = userService.GetUserId();

            logger.LogWarning(
                LogMessageFormatter.FormatWarningLogMessage(Warning, e, userId, GetControllerName(), GetActionName()));

            TempData[ErrorNotification] = GeneralErrorMessage;

            return RedirectToAction("HandleErrors", "Error", new { statusCode = 500 });
        }
    }

    [HttpGet]
    [AllowAnonymous]

    public async Task<IActionResult> Read(string compositionId)
    {
        try
        {
            CompositionReadViewModel? compositionReadViewModel = await compositionService.GetByIdAsync(compositionId);

            if (compositionReadViewModel == null)
            {
                TempData[ErrorNotification] =
                    string.Format(ResourceNotFoundErrorMessage, GetControllerName().ToLower());

                return RedirectToAction("HandleErrors", "Error", new { statusCode = 404 });
            }

            compositionReadViewModel.Genres = await genreService.GetByIdAsync(compositionId);

            //TODO: Add comments, ratings, comments, tags if necessary

            return View(compositionReadViewModel);
        }
        catch (Exception e)
        {
            string? userId = userService.GetUserId();

            logger.LogWarning(
                LogMessageFormatter.FormatWarningLogMessage(Warning, e, userId, GetControllerName(), GetActionName()));

            TempData[ErrorNotification] = GeneralErrorMessage;

            return RedirectToAction("HandleErrors", "Error", new { statusCode = 500 });
        }
    }

    [HttpPost]

    public async Task<IActionResult> Delete(string compositionId)
    {
        try
        {
            await compositionService.DeleteByIdAsync(compositionId);

            TempData[SuccessNotification] =
                string.Format(SuccessfulResourceDeletionMessage, GetControllerName().ToLower());

            return RedirectToAction("User", "Deleted");
        }
        catch (Exception e)
        {
            string? userId = userService.GetUserId();

            logger.LogWarning(
                LogMessageFormatter.FormatWarningLogMessage(Warning, e, userId, GetControllerName(), GetActionName()));

            TempData[ErrorNotification] = GeneralErrorMessage;

            return RedirectToAction("HandleErrors", "Error", new { statusCode = 500 });
        }
    }

    [HttpGet]

    public async Task<IActionResult> Edit(string compositionId)
    {
        CompositionFormModel? compositionFormModel = await compositionService.GetForEditAsync(compositionId);

        string? userId = userService.GetUserId();

        if (userId == null)
        {
            TempData[ErrorNotification] = FailedEditingCompositionErrorMessage;

            return RedirectToAction("All");
        }

        try
        {
            if (compositionFormModel == null)
            {
                TempData[ErrorNotification] =
                    string.Format(ResourceNotFoundErrorMessage, GetControllerName().ToLower());

                return RedirectToAction("HandleErrors", "Error", new { statusCode = 404 });
            }

            if (userId != compositionFormModel.AuthorId && !await accountService.IsInRoleAsync(userId, AdminRoleName))
            {
                TempData[WarningNotification] = UnauthorizedErrorMessage;

                return RedirectToAction("HandleErrors", "Error", new { statusCode = 401 });
            }

            compositionFormModel.GenresToSelect = await genreService.GetAllForSelectAsync();

            return View(compositionFormModel);
        }
        catch (Exception e)
        {
            logger.LogWarning(
                LogMessageFormatter.FormatWarningLogMessage(Warning, e, userId, GetControllerName(), GetActionName()));

            TempData[ErrorNotification] = GeneralErrorMessage;

            return RedirectToAction("HandleErrors", "Error", new { statusCode = 500 });
        }
    }

    [HttpPost]

    public async Task<IActionResult> Edit(CompositionFormModel formModel)
    {
        try
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, InvalidInputDataErrorMessage);

                formModel.GenresToSelect = await genreService.GetAllForSelectAsync();

                TempData[ErrorNotification] = InvalidInputDataErrorMessage;

                return View(formModel);
            }

            await genreService.RemoveFromCompositionAsync(formModel.Id!, formModel.Genres);

            await genreService.AddToCompositionAsync(formModel.Id!, formModel.Genres);

            await compositionService.UpdateAsync(formModel);

            TempData[SuccessNotification] =
                string.Format(SuccessfulResourceUpdateMessage,
                    GetControllerName().ToLower(),
                    formModel.Title);

            return RedirectToAction("Read", new { CompositionId = formModel.Id });
        }
        catch (Exception e)
        {
            string? userId = userService.GetUserId();

            logger.LogWarning(

Fabula.Web/Controllers/RatingController.cs
namespace Fabula.Web.Controllers;

using Microsoft.AspNetCore.Mvc;

using System.Web.Mvc;

public class RatingController : BaseController
{
    public IActionResult Index()
    {
        return View();
    }

    [ChildActionOnly]

    public async Task<IActionResult> CompositionPreview()
    {
        return View("_RatingPreviewPartial");
    }
}

Fabula.Web/ViewComponents/CommentsPreviewViewComponent.cs
namespace Fabula.Web.ViewComponents;

using Core.Contracts;
using ViewModels.Comment;

using Microsoft.AspNetCore.Mvc;

public class CommentsPreviewViewComponent : ViewComponent
{
    private readonly ICommentService commentService;

    public CommentsPreviewViewComponent(ICommentService commentService)
    {
        this.commentService = commentService;
    }

    public async Task<IViewComponentResult> InvokeAsync(int numberOfComments, string compositionId)
    {
        IEnumerable<CommentCompositionViewModel> commentViewModels = await commentService.GetForPreviewByIdAsync(compositionId);

        return View("_CommentsPreviewPartial", commentViewModels.Take(numberOfComments));
    }
}

Fabula.Web/ViewComponents/RatingsPreviewViewComponent.cs
namespace Fabula.Web.ViewComponents;

using Core.Contracts;
using ViewModels.Rating;

using Microsoft.AspNetCore.Mvc;

public class RatingsPreviewViewComponent : ViewComponent
{
    private readonly IRatingService ratingService;

    public RatingsPreviewViewComponent(IRatingService ratingService)
    {
        this.ratingService = ratingService;
    }

    public async Task<IViewComponentResult> InvokeAsync(int numberOfRatings, string compositionId)
    {
        IEnumerable<RatingViewModel> ratingViewModels = await ratingService.GetRatingsByIdAsync(compositionId);

        return View("_RatingsPreviewPartial", ratingViewModels.Take(numberOfRatings));
    }
}

Fabula.Web/Views/Composition/All.cshtml
@using System.Globalization;
@model CompositionQueryModel
@{
    string possessiveS = "\'s";

    ViewData["Title"] = $"{(Model.Username != null ? Model.Username + possessiveS : null)} Works";
}

@if (Model.Username != null)
{
    <h1 class="text-center">
        <a style="text-decoration: none" asp-controller="User" asp-action="Profile" asp-route-userId="@Model.UserId">@Model.Username</a>'s Works
    </h1>
}
else
{
    <h1 class="text-center">@ViewData["Title"]</h1>
}
<hr />
<form method="get">
    <div class="container">
        <div class="row">
            <div class="form-select">
                <label asp-for="SelectedGenres">Genres:</label>
                <select asp-for="SelectedGenres" class="form-control" multiple="true">
                    <option value="">All</option>
                    @foreach (GenreViewModel genre in Model.Genres.OrderBy(g => g.Name))
                    {
                        <option value="@genre.Id">@genre.Name</option>
                    }
                </select>
            </div>
            <div class="form-group col-md-3">
                <label asp-for="SearchTerm">Search term:</label>
                <input asp-for="SearchTerm" class="form-control" placeholder="Search term...">
            </div>
            <div class="form-group col-md-3">
                <div class="form-group">
                    <label asp-for="DateSorting">Sort by date:</label>
                    <select asp-for="DateSorting" class="form-control">
                        <option value="1">Newest first</option>
                        <option value="0">Oldest first</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-3">
                <div class="form-group">
                    <label asp-for="RatingSorting">Sort by rating:</label>
                    <select asp-for="RatingSorting" class="form-control">
                        <option value="1">Top rated first</option>
                        <option value="0">Worst rated first</option>
                    </select>
                </div>
            </div>
            <input hidden asp-for="UserId" class="form-control" value="@Model.UserId">
            <div class="form-group col-md-3">
                <div class="form-group mt-4">
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
</form>
@{
    int previousPage = Model.CurrentPage - 1;

    if (previousPage < 1)
    {
        previousPage = 1;
    }

    double maxPage = Math.Ceiling((double)Model.CompositionsCount / Model.CompositionsPerPage);
}
<div class="container" style="margin-top: 1rem">
    <div class="row mb-5">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
                   asp-controller="Composition"
                   asp-action="All"
                   asp-route-userId="@Model.UserId"
                   asp-route-currentPage="1"
                   asp-route-selectedGenres="@($"{(!Model.SelectedGenres.Any() ? "" : Model.SelectedGenres)}")"
                   asp-route-searchTerm="@Model.SearchTerm"
                   asp-route-dateSorting="@((int)Model.DateSorting)"
                   asp-route-ratingSorting="@((int)Model.RatingSorting)">@Html.Raw("<<")</a>
            </li>
            <li class="page-item">
                <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
                   asp-controller="Composition"
                   asp-action="All"
                   asp-route-userId="@Model.UserId"
                   asp-route-currentPage="@previousPage"
                   asp-route-selectedGenres="@($"{(!Model.SelectedGenres.Any() ? "" : Model.SelectedGenres)}")"
                   asp-route-searchTerm="@Model.SearchTerm"
                   asp-route-dateSorting="@((int)Model.DateSorting)"
                   asp-route-ratingSorting="@((int)Model.RatingSorting)">
                    @Html.Raw("<")
                </a>
            </li>
            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="btn btn-primary"
                       asp-controller="Composition"
                       asp-action="All"
                       asp-route-userId="@Model.UserId"
                       asp-route-currentPage="@previousPage"
                       asp-route-selectedGenres="@($"{(!Model.SelectedGenres.Any() ? "" : Model.SelectedGenres)}")"
                       asp-route-searchTerm="@Model.SearchTerm"
                       asp-route-dateSorting="@((int)Model.DateSorting)"
                       asp-route-ratingSorting="@((int)Model.RatingSorting)">
                        @previousPage
                    </a>
                </li>
            }
            <li class="page-item" style="margin-left: 1rem; margin-right: 1rem">
                <p class="btn btn-info">@Model.CurrentPage</p>
            </li>
            @if (Model.CurrentPage < maxPage)
            {
                <li class="page-item">
                    <a class="btn btn-primary"
                       asp-controller="Composition"
                       asp-action="All"
                       asp-route-userId="@Model.UserId"
                       asp-route-currentPage="@(Model.CurrentPage + 1)"
                       asp-route-selectedGenres="@($"{(!Model.SelectedGenres.Any() ? "" : Model.SelectedGenres)}")"
                       asp-route-searchTerm="@Model.SearchTerm"
                       asp-route-dateSorting="@((int)Model.DateSorting)"
                       asp-route-ratingSorting="@((int)Model.RatingSorting)">
                        @(Model.CurrentPage + 1)
                    </a>
                </li>
            }
            @{
                bool shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.Compositions.Any();
            }
            <li class="page-item">
                <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
                   asp-controller="Composition"
                   asp-action="All"
                   asp-route-userId="@Model.UserId"
                   asp-route-currentPage="@(Model.CurrentPage + 1)"
                   asp-route-selectedGenres="@($"{(!Model.SelectedGenres.Any() ? "" : Model.SelectedGenres)}")"
                   asp-route-searchTerm="@Model.SearchTerm"
                   asp-route-dateSorting="@((int)Model.DateSorting)"
                   asp-route-ratingSorting="@((int)Model.RatingSorting)">
                    @Html.Raw(">")
                </a>
            </li>
            <li class="page-item">
                <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
                   asp-controller="Composition"
                   asp-action="All"
                   asp-route-userId="@Model.UserId"
                   asp-route-currentPage="@maxPage"
                   asp-route-selectedGenres="@($"{(!Model.SelectedGenres.Any() ? "" : Model.SelectedGenres)}")"
                   asp-route-searchTerm="@Model.SearchTerm"
                   asp-route-dateSorting="@((int)Model.DateSorting)"
                   asp-route-ratingSorting="@((int)Model.RatingSorting)">
                    @Html.Raw(">>")
                </a>
            </li>
        </ul>
    </div>
</div>
@if (!Model.Compositions.Any())
{
    <h2 class="text-center">No compositions found with the given criteria!</h2>
}
else
{
    <div class="row row-cols-1 row-cols-md-3 g-4">

        @foreach (CompositionViewModel composition in Model.Compositions)
        {
            <div class="col">
                <partial name="_CompositionAllPartial" model="composition"></partial>
            </div>
        }

    </div>
}

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Fabula.Web/Views/Composition/Create.cshtml
@model CompositionFormModel
@{
    ViewData["Title"] = "Write your own piece";
}

<h1 class="text-center">@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <partial name="_CompositionFormPartial" model="@Model"></partial>

            <div class="text-center">
                <input class="btn btn-primary mt-3 btn-primary" type="submit" value="Create" />
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

    <script>
        var simplemde = new SimpleMDE({
            element: document.getElementById("content-textarea"),
            status: ["autosave", "lines", "words"]
        });
    </script>
}

Fabula.Web/Views/Composition/Edit.cshtml
@using System.Security.Claims;
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> userManager;
@model CompositionFormModel
@{
    ViewData["Title"] = $"Edit {Model.Title}";

    string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

    ApplicationUser? user = await userManager.FindByIdAsync(userId);

    bool isAuthenticated = User?.Identity?.IsAuthenticated ?? false;
    bool isAuthor = User.FindFirstValue(ClaimTypes.NameIdentifier) == Model.AuthorId;
    bool isAdmin = await userManager.IsInRoleAsync(user, "Admin");
}

<h1 class="text-center">Edit</h1>
<div class="text-center">
    <h2>@Model.Title</h2>
</div>
<hr />
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <partial name="_CompositionFormPartial" model="@Model"></partial>
            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
            </div>
            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Edit" />
            </div>
        </form>

        @if (isAuthenticated && isAuthor || isAdmin)
        {
            <hr />
            <h2 class="text-danger text-center" style="margin-top: 2rem">Delete your work</h2>
            <form onsubmit="return confirmAction();" method="post" asp-action="Delete" asp-route-compositionid="@Model.Id">
                <div class="text-center">
                    <input type="submit" value="Delete" class="btn btn-danger mt-3" />
                </div>
            </form>
        }
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

    <script>
        function confirmAction() {
            var confirmed = window.confirm("Are you sure you want to delete your work? Once deleted your work can only be recovered within a 30 day time period!");
            return confirmed;
        }
    </script>

    <script>
        var simplemde = new SimpleMDE({
            element: document.getElementById("content-textarea"),
            status: ["autosave", "lines", "words"]
        });
    </script>
}

Fabula.Web/Views/Composition/Read.cshtml
@using System.Security.Claims;
@using Microsoft.AspNetCore.Identity;
@inject UserManager<ApplicationUser> userManager
@model CompositionReadViewModel
@{
    ViewData["Title"] = Model.Title;

    string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

    ApplicationUser? user = null;

    bool isAuthenticated = User?.Identity?.IsAuthenticated ?? false;

    bool isAuthor = false;
    bool isAdmin = false;

    if (isAuthenticated)
    {
        user = await userManager.FindByIdAsync(userId);
        isAuthor = User.FindFirstValue(ClaimTypes.NameIdentifier) == Model?.Author?.Id;
        isAdmin = await userManager.IsInRoleAsync(user, AdminRoleName);
    }

}

<div class="container">
    <div class="row">
        <div class="col-sm-2">
            <a asp-controller="Rating" asp-action="All" asp-route-compositionid="@Model?.Id" class="btn btn-primary">All ratings</a>
            @await Component.InvokeAsync("RatingsPreview", new { numberOfRatings = 6, compositionId = Model?.Id})
        </div>
        <div class="col-md-8">
            <div class="card text-bg-info">
                <div class="card-body">
                    <img src="@Model?.CoverUrl" class="card-img-top" alt="Image not found :(" />
                    <h1 class="text-center" style="padding-top: 20px">@Model?.Title</h1>
                    <p class="text-center" style="text-decoration: none; font-size: small">
                        Written by:
                        <a asp-controller="User" asp-action="Profile" asp-route-userid="@Model?.Author?.Id" style="text-decoration: none">@Model?.Author?.Username</a>
                    </p>
                    <br />
                    <p class="text-center" style="font-size: small">
                        Genres:
                    </p>
                    <p class="text-center" style="text-decoration: none; font-size: small">
                        @for (int i = 0; i < Model?.Genres.Count(); i++)
                        {
                            <a asp-controller="Composition"
                               asp-action="All"
                               asp-route-currentPage=""
                               asp-route-selectedGenres="@Model.Genres.ToArray()[i].Id"
                               asp-route-searchTerm=""
                               asp-route-dateSorting=""
                               asp-route-ratingSorting="">
                                @Model.Genres.ToArray()[i].Name
                            </a>
                        }
                    </p>
                    <textarea disabled>@Model?.Content</textarea>
                    @if (isAuthenticated && isAuthor || isAdmin)
                    {
                        <div class="text-center" style="margin-top: 2rem">
                            <a asp-action="Edit" asp-route-compositionid="@Model?.Id" class="btn btn-primary mt-3">Edit</a>
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="col-sm-2">
            <a asp-controller="Comment" asp-action="All" asp-route-compositionid="@Model?.Id" class="btn btn-primary text-center">All comments</a>
            @await Component.InvokeAsync("CommentsPreview", new { numberOfComments = 6, compositionId = Model?.Id})
        </div>
    </div>
</div>

@section Scripts{
    <script>
        var simplemde = new SimpleMDE({
            toolbar: false,
            tabSize: 4,
            status: false
        })

        simplemde.togglePreview();
    </script>
}