Fabula.Web/Controllers/CommentController.cs
namespace Fabula.Web.Controllers;

using Core.Contracts;
using ViewModels.Comment;
using Infrastructure.Utilities;

using static Common.Messages.LoggerMessages;
using static Common.Messages.NotificationTypes;
using static Common.Messages.ErrorMessages.Shared;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using System.Security.Claims;

public class CommentController : BaseController
{
    private readonly ICommentService commentService;

    private readonly ILogger logger;

    public CommentController(ICommentService commentService, ILogger<CommentController> logger)
    {
        this.commentService = commentService;
        this.logger = logger;
    }

    public async Task<IActionResult> All(string compositionId)
    {
        try
        {
            CommentsAllViewModel? commentViewModels = await commentService.GetAllByIdAsync(compositionId);

            if (commentViewModels == null)
            {
                TempData[WarningNotification] =
                    string.Format(ResourceNotFoundErrorMessage, GetControllerName().ToLower());

                return RedirectToAction("HandleErrors", "Error", new { statusCode = 404 });
            }

            return View(commentViewModels);
        }
        catch (Exception e)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            logger.LogWarning(
                LogMessageFormatter.FormatWarningLogMessage(Warning, e, userId, GetControllerName(), GetActionName()));

            TempData[ErrorNotification] = GeneralErrorMessage;

            return RedirectToAction("HandleErrors", "Error", new { statusCode = 500 });
        }
    }
}

Fabula.Web/Controllers/UserController.cs
namespace Fabula.Web.Controllers;

using Core.Contracts;
using ViewModels.User;
using Infrastructure.Utilities;

using static Common.Messages.LoggerMessages;
using static Common.Messages.NotificationTypes;
using static Common.Messages.ErrorMessages.Genre;
using static Common.Messages.ErrorMessages.Shared;
using static Common.Messages.SuccessMessages.Genre;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;

using System.Security.Claims;

public class UserController : BaseController
{
    private readonly IUserService userService;

    private readonly ICompositionService compositionService;

    private readonly IGenreService genreService;

    private readonly ILogger logger;

    public UserController(
        IUserService userService,
        ICompositionService compositionService,
        IGenreService genreService,
        ILogger<UserController> logger)
    {
        this.userService = userService;
        this.compositionService = compositionService;
        this.genreService = genreService;
        this.logger = logger;
    }

    [HttpGet]
    [AllowAnonymous]

    public async Task<IActionResult> Profile(string userId)
    {
        try
        {
            UserProfileViewModel? profileViewModel = await userService.GetProfileAsync(userId);

            if (profileViewModel == null)
            {
                TempData[WarningNotification] =
                    string.Format(ResourceNotFoundErrorMessage, GetControllerName().ToLower());

                return RedirectToAction("HandleErrors", "Error", new { statusCode = 404 });
            }

            profileViewModel.FavoriteGenres = await genreService.GetForUserAsync(userId);

            return View(profileViewModel);
        }
        catch (Exception e)
        {
            string? user = User.FindFirstValue(ClaimTypes.NameIdentifier);

            logger.LogWarning(
                LogMessageFormatter.FormatWarningLogMessage(Warning, e, userId, GetControllerName(), GetActionName()));

            TempData[ErrorNotification] = GeneralErrorMessage;

            return RedirectToAction("HandleErrors", "Error", new { statusCode = 500 });
        }
    }

    [HttpPost]

    public async Task<IActionResult> FavoriteGenre(int genreId)
    {
        string? userId = userService.GetUserId();

        try
        {
            if (userId != null)
            {
                await userService.AddFavoriteGenreToUserAsync(userId, genreId);

                TempData[SuccessNotification] = SuccessfulFavoriteGenreAddMessage;

                return RedirectToAction("Profile", new { UserId = userId });
            }

            TempData[ErrorNotification] = FailedGenreFavoriteAddition;

            return RedirectToAction("All", "Genre");
        }
        catch (Exception e)
        {
            logger.LogWarning(
                LogMessageFormatter.FormatWarningLogMessage(Warning, e, userId, GetControllerName(), GetActionName()));

            TempData[ErrorNotification] = GeneralErrorMessage;

            return RedirectToAction("HandleErrors", "Error", new { statusCode = 500 });
        }
    }

    [HttpPost]

    public async Task<IActionResult> UnfavoriteGenre(int genreId)
    {
        string? userId = userService.GetUserId();

        try
        {
            if (userId != null)
            {
                await userService.RemoveFavoriteGenreFromUserAsync(userId, genreId);

                TempData[SuccessNotification] = SuccessfulFavoriteGenreRemoveMessage;

                return RedirectToAction("Profile", new { UserId = userId });
            }

            TempData[ErrorNotification] = FailedGenreFavoriteRemoval;

            return RedirectToAction("Profile", new { UserId = userId });
        }
        catch (Exception e)
        {
            logger.LogWarning(
                LogMessageFormatter.FormatWarningLogMessage(Warning, e, userId, GetControllerName(), GetActionName()));

            TempData[ErrorNotification] = GeneralErrorMessage;

            return RedirectToAction("HandleErrors", "Error", new { statusCode = 500 });
        }
    }
}

Fabula.Web/Views/Composition/Components/CommentsPreview/_CommentsPreviewPartial.cshtml
@model IEnumerable<CommentCompositionViewModel>

@foreach (CommentCompositionViewModel comment in Model)
{
    <div class="row">
        <div class="container">
            <div class="card text-bg-primary">
                <div class="card-body">
                    <div class="col">
                        <img class="rounded-circle me-1" src="@comment?.Author?.ProfilePictureUrl" alt="Image not found :(" height="30" width="30" />
                    </div>
                    <h5 class="card-title">
                        <a asp-controller="User" asp-action="Profile" asp-route-userId="@comment?.Author?.Id" style="text-decoration: none">
                            ($"@{@comment?.Author?.Username}")
                        </a>
                    </h5>
                    <p class="card-text">@comment?.Content</p>
                    <div class="card-footer">
                        <p class="card-text">Posted on: @comment?.PublishedOn.ToString()</p>
                        <a class="card-link" asp-controller="Comment" asp-action="Read" asp-route-commentId="@comment?.Id" style="text-decoration: none">
                            @comment?.Likes likes
                        </a>
                        <a class="card-link" asp-controller="Comment" asp-action="Read" asp-route-commentId="@comment?.Id" style="text-decoration: none">
                            @comment?.Replies replies
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}